apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: -Namespace-
  labels:
    app: web
spec:
  ports:
    - port: 80
  selector:
    app: web
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: -Namespace-
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      imagePullSecrets:
        - name: ecr-token
      containers:
        - name: web
          image: -Image_Name-
          ports:
          - containerPort: 80 
